version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql
    environment:
      MYSQL_DB: ${MYSQL_DB:-news_parser}
      # You should definitely change the password in production
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-root}
    volumes:
      - database_data:/var/lib/mysql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
